// 国家和地区数据：国家列表、国家代码映射和州/省数据
// ISO 3166-1 标准国家列表（按字母顺序）
export const COUNTRIES = [
  { name: 'Afghanistan', nameZh: '阿富汗', code: 'AF' },
  { name: 'Albania', nameZh: '阿尔巴尼亚', code: 'AL' },
  { name: 'Algeria', nameZh: '阿尔及利亚', code: 'DZ' },
  { name: 'Andorra', nameZh: '安道尔', code: 'AD' },
  { name: 'Angola', nameZh: '安哥拉', code: 'AO' },
  { name: 'Anguilla', nameZh: '安圭拉', code: 'AI' },
  { name: 'Antigua and Barbuda', nameZh: '安提瓜和巴布达', code: 'AG' },
  { name: 'Argentina', nameZh: '阿根廷', code: 'AR' },
  { name: 'Armenia', nameZh: '亚美尼亚', code: 'AM' },
  { name: 'Aruba', nameZh: '阿鲁巴', code: 'AW' },
  { name: 'Australia', nameZh: '澳大利亚', code: 'AU' },
  { name: 'Austria', nameZh: '奥地利', code: 'AT' },
  { name: 'Azerbaijan', nameZh: '阿塞拜疆', code: 'AZ' },
  { name: 'Bahamas', nameZh: '巴哈马', code: 'BS' },
  { name: 'Bahrain', nameZh: '巴林', code: 'BH' },
  { name: 'Bangladesh', nameZh: '孟加拉国', code: 'BD' },
  { name: 'Barbados', nameZh: '巴巴多斯', code: 'BB' },
  { name: 'Belarus', nameZh: '白俄罗斯', code: 'BY' },
  { name: 'Belgium', nameZh: '比利时', code: 'BE' },
  { name: 'Belize', nameZh: '伯利兹', code: 'BZ' },
  { name: 'Benin', nameZh: '贝宁', code: 'BJ' },
  { name: 'Bermuda', nameZh: '百慕大', code: 'BM' },
  { name: 'Bhutan', nameZh: '不丹', code: 'BT' },
  { name: 'Bolivia', nameZh: '玻利维亚', code: 'BO' },
  { name: 'Bosnia and Herzegovina', nameZh: '波黑', code: 'BA' },
  { name: 'Botswana', nameZh: '博茨瓦纳', code: 'BW' },
  { name: 'Brazil', nameZh: '巴西', code: 'BR' },
  { name: 'British Indian Ocean Territory', nameZh: '英属印度洋领地', code: 'IO' },
  { name: 'Brunei', nameZh: '文莱', code: 'BN' },
  { name: 'Bulgaria', nameZh: '保加利亚', code: 'BG' },
  { name: 'Burkina Faso', nameZh: '布基纳法索', code: 'BF' },
  { name: 'Burundi', nameZh: '布隆迪', code: 'BI' },
  { name: 'Cambodia', nameZh: '柬埔寨', code: 'KH' },
  { name: 'Cameroon', nameZh: '喀麦隆', code: 'CM' },
  { name: 'Canada', nameZh: '加拿大', code: 'CA' },
  { name: 'Cape Verde', nameZh: '佛得角', code: 'CV' },
  { name: 'Cayman Islands', nameZh: '开曼群岛', code: 'KY' },
  { name: 'Central African Republic', nameZh: '中非共和国', code: 'CF' },
  { name: 'Chad', nameZh: '乍得', code: 'TD' },
  { name: 'Chile', nameZh: '智利', code: 'CL' },
  { name: 'China', nameZh: '中国', code: 'CN' },
  { name: 'Colombia', nameZh: '哥伦比亚', code: 'CO' },
  { name: 'Comoros', nameZh: '科摩罗', code: 'KM' },
  { name: 'Congo', nameZh: '刚果', code: 'CG' },
  { name: 'Cook Islands', nameZh: '库克群岛', code: 'CK' },
  { name: 'Costa Rica', nameZh: '哥斯达黎加', code: 'CR' },
  { name: 'Croatia', nameZh: '克罗地亚', code: 'HR' },
  { name: 'Cuba', nameZh: '古巴', code: 'CU' },
  { name: 'Curacao', nameZh: '库拉索', code: 'CW' },
  { name: 'Cyprus', nameZh: '塞浦路斯', code: 'CY' },
  { name: 'Czech Republic', nameZh: '捷克', code: 'CZ' },
  { name: 'Democratic Republic of Congo', nameZh: '刚果民主共和国', code: 'CD' },
  { name: 'Denmark', nameZh: '丹麦', code: 'DK' },
  { name: 'Djibouti', nameZh: '吉布提', code: 'DJ' },
  { name: 'Dominica', nameZh: '多米尼克', code: 'DM' },
  { name: 'Dominican Republic', nameZh: '多米尼加共和国', code: 'DO' },
  { name: 'Ecuador', nameZh: '厄瓜多尔', code: 'EC' },
  { name: 'Egypt', nameZh: '埃及', code: 'EG' },
  { name: 'El Salvador', nameZh: '萨尔瓦多', code: 'SV' },
  { name: 'Equatorial Guinea', nameZh: '赤道几内亚', code: 'GQ' },
  { name: 'Eritrea', nameZh: '厄立特里亚', code: 'ER' },
  { name: 'Estonia', nameZh: '爱沙尼亚', code: 'EE' },
  { name: 'Eswatini', nameZh: '斯威士兰', code: 'SZ' },
  { name: 'Ethiopia', nameZh: '埃塞俄比亚', code: 'ET' },
  { name: 'Falkland Islands', nameZh: '福克兰群岛', code: 'FK' },
  { name: 'Faroe Islands', nameZh: '法罗群岛', code: 'FO' },
  { name: 'Fiji', nameZh: '斐济', code: 'FJ' },
  { name: 'Finland', nameZh: '芬兰', code: 'FI' },
  { name: 'France', nameZh: '法国', code: 'FR' },
  { name: 'French Guiana', nameZh: '法属圭亚那', code: 'GF' },
  { name: 'French Polynesia', nameZh: '法属波利尼西亚', code: 'PF' },
  { name: 'Gabon', nameZh: '加蓬', code: 'GA' },
  { name: 'Gambia', nameZh: '冈比亚', code: 'GM' },
  { name: 'Georgia', nameZh: '格鲁吉亚', code: 'GE' },
  { name: 'Germany', nameZh: '德国', code: 'DE' },
  { name: 'Ghana', nameZh: '加纳', code: 'GH' },
  { name: 'Gibraltar', nameZh: '直布罗陀', code: 'GI' },
  { name: 'Greece', nameZh: '希腊', code: 'GR' },
  { name: 'Greenland', nameZh: '格陵兰', code: 'GL' },
  { name: 'Grenada', nameZh: '格林纳达', code: 'GD' },
  { name: 'Guadeloupe', nameZh: '瓜德罗普', code: 'GP' },
  { name: 'Guam', nameZh: '关岛', code: 'GU' },
  { name: 'Guatemala', nameZh: '危地马拉', code: 'GT' },
  { name: 'Guernsey', nameZh: '根西岛', code: 'GG' },
  { name: 'Guinea', nameZh: '几内亚', code: 'GN' },
  { name: 'Guinea-Bissau', nameZh: '几内亚比绍', code: 'GW' },
  { name: 'Guyana', nameZh: '圭亚那', code: 'GY' },
  { name: 'Haiti', nameZh: '海地', code: 'HT' },
  { name: 'Honduras', nameZh: '洪都拉斯', code: 'HN' },
  { name: 'Hong Kong', nameZh: '香港', code: 'HK' },
  { name: 'Hungary', nameZh: '匈牙利', code: 'HU' },
  { name: 'Iceland', nameZh: '冰岛', code: 'IS' },
  { name: 'India', nameZh: '印度', code: 'IN' },
  { name: 'Indonesia', nameZh: '印度尼西亚', code: 'ID' },
  { name: 'Iran', nameZh: '伊朗', code: 'IR' },
  { name: 'Iraq', nameZh: '伊拉克', code: 'IQ' },
  { name: 'Ireland', nameZh: '爱尔兰', code: 'IE' },
  { name: 'Isle of Man', nameZh: '马恩岛', code: 'IM' },
  { name: 'Israel', nameZh: '以色列', code: 'IL' },
  { name: 'Italy', nameZh: '意大利', code: 'IT' },
  { name: 'Ivory Coast', nameZh: '科特迪瓦', code: 'CI' },
  { name: 'Jamaica', nameZh: '牙买加', code: 'JM' },
  { name: 'Japan', nameZh: '日本', code: 'JP' },
  { name: 'Jersey', nameZh: '泽西岛', code: 'JE' },
  { name: 'Jordan', nameZh: '约旦', code: 'JO' },
  { name: 'Kazakhstan', nameZh: '哈萨克斯坦', code: 'KZ' },
  { name: 'Kenya', nameZh: '肯尼亚', code: 'KE' },
  { name: 'Kiribati', nameZh: '基里巴斯', code: 'KI' },
  { name: 'Kosovo', nameZh: '科索沃', code: 'XK' },
  { name: 'Kuwait', nameZh: '科威特', code: 'KW' },
  { name: 'Kyrgyzstan', nameZh: '吉尔吉斯斯坦', code: 'KG' },
  { name: 'Laos', nameZh: '老挝', code: 'LA' },
  { name: 'Latvia', nameZh: '拉脱维亚', code: 'LV' },
  { name: 'Lebanon', nameZh: '黎巴嫩', code: 'LB' },
  { name: 'Lesotho', nameZh: '莱索托', code: 'LS' },
  { name: 'Liberia', nameZh: '利比里亚', code: 'LR' },
  { name: 'Libya', nameZh: '利比亚', code: 'LY' },
  { name: 'Liechtenstein', nameZh: '列支敦士登', code: 'LI' },
  { name: 'Lithuania', nameZh: '立陶宛', code: 'LT' },
  { name: 'Luxembourg', nameZh: '卢森堡', code: 'LU' },
  { name: 'Macao', nameZh: '澳门', code: 'MO' },
  { name: 'Madagascar', nameZh: '马达加斯加', code: 'MG' },
  { name: 'Malawi', nameZh: '马拉维', code: 'MW' },
  { name: 'Malaysia', nameZh: '马来西亚', code: 'MY' },
  { name: 'Maldives', nameZh: '马尔代夫', code: 'MV' },
  { name: 'Mali', nameZh: '马里', code: 'ML' },
  { name: 'Malta', nameZh: '马耳他', code: 'MT' },
  { name: 'Marshall Islands', nameZh: '马绍尔群岛', code: 'MH' },
  { name: 'Martinique', nameZh: '马提尼克', code: 'MQ' },
  { name: 'Mauritania', nameZh: '毛里塔尼亚', code: 'MR' },
  { name: 'Mauritius', nameZh: '毛里求斯', code: 'MU' },
  { name: 'Mayotte', nameZh: '马约特', code: 'YT' },
  { name: 'Mexico', nameZh: '墨西哥', code: 'MX' },
  { name: 'Micronesia', nameZh: '密克罗尼西亚', code: 'FM' },
  { name: 'Moldova', nameZh: '摩尔多瓦', code: 'MD' },
  { name: 'Monaco', nameZh: '摩纳哥', code: 'MC' },
  { name: 'Mongolia', nameZh: '蒙古', code: 'MN' },
  { name: 'Montenegro', nameZh: '黑山', code: 'ME' },
  { name: 'Montserrat', nameZh: '蒙特塞拉特', code: 'MS' },
  { name: 'Morocco', nameZh: '摩洛哥', code: 'MA' },
  { name: 'Mozambique', nameZh: '莫桑比克', code: 'MZ' },
  { name: 'Myanmar', nameZh: '缅甸', code: 'MM' },
  { name: 'Namibia', nameZh: '纳米比亚', code: 'NA' },
  { name: 'Nauru', nameZh: '瑙鲁', code: 'NR' },
  { name: 'Nepal', nameZh: '尼泊尔', code: 'NP' },
  { name: 'Netherlands', nameZh: '荷兰', code: 'NL' },
  { name: 'New Caledonia', nameZh: '新喀里多尼亚', code: 'NC' },
  { name: 'New Zealand', nameZh: '新西兰', code: 'NZ' },
  { name: 'Nicaragua', nameZh: '尼加拉瓜', code: 'NI' },
  { name: 'Niger', nameZh: '尼日尔', code: 'NE' },
  { name: 'Nigeria', nameZh: '尼日利亚', code: 'NG' },
  { name: 'North Macedonia', nameZh: '北马其顿', code: 'MK' },
  { name: 'Northern Mariana Islands', nameZh: '北马里亚纳群岛', code: 'MP' },
  { name: 'Norway', nameZh: '挪威', code: 'NO' },
  { name: 'Oman', nameZh: '阿曼', code: 'OM' },
  { name: 'Pakistan', nameZh: '巴基斯坦', code: 'PK' },
  { name: 'Palau', nameZh: '帕劳', code: 'PW' },
  { name: 'Palestinian Territory', nameZh: '巴勒斯坦', code: 'PS' },
  { name: 'Panama', nameZh: '巴拿马', code: 'PA' },
  { name: 'Papua New Guinea', nameZh: '巴布亚新几内亚', code: 'PG' },
  { name: 'Paraguay', nameZh: '巴拉圭', code: 'PY' },
  { name: 'Peru', nameZh: '秘鲁', code: 'PE' },
  { name: 'Philippines', nameZh: '菲律宾', code: 'PH' },
  { name: 'Poland', nameZh: '波兰', code: 'PL' },
  { name: 'Portugal', nameZh: '葡萄牙', code: 'PT' },
  { name: 'Puerto Rico', nameZh: '波多黎各', code: 'PR' },
  { name: 'Qatar', nameZh: '卡塔尔', code: 'QA' },
  { name: 'Reunion', nameZh: '留尼汪', code: 'RE' },
  { name: 'Romania', nameZh: '罗马尼亚', code: 'RO' },
  { name: 'Russia', nameZh: '俄罗斯', code: 'RU' },
  { name: 'Rwanda', nameZh: '卢旺达', code: 'RW' },
  { name: 'Saint Kitts and Nevis', nameZh: '圣基茨和尼维斯', code: 'KN' },
  { name: 'Saint Lucia', nameZh: '圣卢西亚', code: 'LC' },
  { name: 'Saint Vincent and the Grenadines', nameZh: '圣文森特和格林纳丁斯', code: 'VC' },
  { name: 'Samoa', nameZh: '萨摩亚', code: 'WS' },
  { name: 'San Marino', nameZh: '圣马力诺', code: 'SM' },
  { name: 'Sao Tome and Principe', nameZh: '圣多美和普林西比', code: 'ST' },
  { name: 'Saudi Arabia', nameZh: '沙特阿拉伯', code: 'SA' },
  { name: 'Senegal', nameZh: '塞内加尔', code: 'SN' },
  { name: 'Serbia', nameZh: '塞尔维亚', code: 'RS' },
  { name: 'Seychelles', nameZh: '塞舌尔', code: 'SC' },
  { name: 'Sierra Leone', nameZh: '塞拉利昂', code: 'SL' },
  { name: 'Singapore', nameZh: '新加坡', code: 'SG' },
  { name: 'Sint Maarten', nameZh: '荷属圣马丁', code: 'SX' },
  { name: 'Slovakia', nameZh: '斯洛伐克', code: 'SK' },
  { name: 'Slovenia', nameZh: '斯洛文尼亚', code: 'SI' },
  { name: 'Solomon Islands', nameZh: '所罗门群岛', code: 'SB' },
  { name: 'Somalia', nameZh: '索马里', code: 'SO' },
  { name: 'South Africa', nameZh: '南非', code: 'ZA' },
  { name: 'South Korea', nameZh: '韩国', code: 'KR' },
  { name: 'South Sudan', nameZh: '南苏丹', code: 'SS' },
  { name: 'Spain', nameZh: '西班牙', code: 'ES' },
  { name: 'Sri Lanka', nameZh: '斯里兰卡', code: 'LK' },
  { name: 'St. Pierre and Miquelon', nameZh: '圣皮埃尔和密克隆', code: 'PM' },
  { name: 'Sudan', nameZh: '苏丹', code: 'SD' },
  { name: 'Suriname', nameZh: '苏里南', code: 'SR' },
  { name: 'Sweden', nameZh: '瑞典', code: 'SE' },
  { name: 'Switzerland', nameZh: '瑞士', code: 'CH' },
  { name: 'Syria', nameZh: '叙利亚', code: 'SY' },
  { name: 'Taiwan', nameZh: '台湾', code: 'TW' },
  { name: 'Tajikistan', nameZh: '塔吉克斯坦', code: 'TJ' },
  { name: 'Tanzania', nameZh: '坦桑尼亚', code: 'TZ' },
  { name: 'Thailand', nameZh: '泰国', code: 'TH' },
  { name: 'Timor-Leste', nameZh: '东帝汶', code: 'TL' },
  { name: 'Togo', nameZh: '多哥', code: 'TG' },
  { name: 'Tonga', nameZh: '汤加', code: 'TO' },
  { name: 'Trinidad and Tobago', nameZh: '特立尼达和多巴哥', code: 'TT' },
  { name: 'Tunisia', nameZh: '突尼斯', code: 'TN' },
  { name: 'Turkey', nameZh: '土耳其', code: 'TR' },
  { name: 'Turkmenistan', nameZh: '土库曼斯坦', code: 'TM' },
  { name: 'Turks and Caicos Islands', nameZh: '特克斯和凯科斯群岛', code: 'TC' },
  { name: 'Tuvalu', nameZh: '图瓦卢', code: 'TV' },
  { name: 'Uganda', nameZh: '乌干达', code: 'UG' },
  { name: 'Ukraine', nameZh: '乌克兰', code: 'UA' },
  { name: 'United Arab Emirates', nameZh: '阿联酋', code: 'AE' },
  { name: 'United Kingdom', nameZh: '英国', code: 'GB' },
  { name: 'United States', nameZh: '美国', code: 'US' },
  { name: 'Uruguay', nameZh: '乌拉圭', code: 'UY' },
  { name: 'Uzbekistan', nameZh: '乌兹别克斯坦', code: 'UZ' },
  { name: 'Vanuatu', nameZh: '瓦努阿图', code: 'VU' },
  { name: 'Vatican City', nameZh: '梵蒂冈', code: 'VA' },
  { name: 'Venezuela', nameZh: '委内瑞拉', code: 'VE' },
  { name: 'Vietnam', nameZh: '越南', code: 'VN' },
  { name: 'Virgin Islands, British', nameZh: '英属维尔京群岛', code: 'VG' },
  { name: 'Virgin Islands, U.S.', nameZh: '美属维尔京群岛', code: 'VI' },
  { name: 'Wallis and Futuna', nameZh: '瓦利斯和富图纳', code: 'WF' },
  { name: 'Yemen', nameZh: '也门', code: 'YE' },
  { name: 'Zambia', nameZh: '赞比亚', code: 'ZM' },
  { name: 'Zimbabwe', nameZh: '津巴布韦', code: 'ZW' }
];

// 国家代码映射
export const COUNTRY_CODES = COUNTRIES.reduce((acc, country) => {
  acc[country.name] = country.code;
  return acc;
}, {});

// 国家和州/省数据（仅包含需要显示州/省下拉菜单的国家，按字母顺序排列）
export const COUNTRY_STATES = {
  'Argentina': [
    'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 'Entre Ríos', 'Formosa',
    'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta',
    'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego',
    'Tucumán', 'Autonomous City of Buenos Aires'
  ],
  'Australia': [
    'Australian Capital Territory', 'New South Wales', 'Northern Territory', 'Queensland',
    'South Australia', 'Tasmania', 'Victoria', 'Western Australia'
  ],
  'Brazil': [
    'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito Federal', 'Espírito Santo',
    'Goiás', 'Maranhão', 'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará', 'Paraíba',
    'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro', 'Rio Grande do Norte', 'Rio Grande do Sul',
    'Rondônia', 'Roraima', 'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins'
  ],
  'Canada': [
    'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
    'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
    'Quebec', 'Saskatchewan', 'Yukon'
  ],
  'China': [
    'Beijing', 'Shanghai', 'Tianjin', 'Chongqing', 'Guangdong', 'Jiangsu', 'Shandong', 'Zhejiang',
    'Henan', 'Sichuan', 'Hubei', 'Fujian', 'Hunan', 'Anhui', 'Hebei', 'Liaoning', 'Jiangxi',
    'Yunnan', 'Guangxi', 'Shanxi', 'Guizhou', 'Heilongjiang', 'Jilin', 'Gansu', 'Hainan',
    'Ningxia', 'Qinghai', 'Xinjiang', 'Tibet', 'Inner Mongolia', 'Hong Kong', 'Macau'
  ],
  'Colombia': [
    'Amazonas', 'Antioquia', 'Arauca', 'Atlántico', 'Bolívar', 'Boyacá', 'Caldas', 'Caquetá',
    'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Córdoba', 'Cundinamarca', 'Guainía', 'Guaviare',
    'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño', 'Norte de Santander', 'Putumayo', 'Quindío',
    'Risaralda', 'San Andrés y Providencia', 'Santander', 'Sucre', 'Tolima', 'Valle del Cauca',
    'Vaupés', 'Vichada'
  ],
  'France': [
    'Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Brittany', 'Centre-Val de Loire',
    'Corsica', 'Grand Est', 'Hauts-de-France', 'Île-de-France', 'Normandy', 'Nouvelle-Aquitaine',
    'Occitanie', 'Pays de la Loire', 'Provence-Alpes-Côte d\'Azur'
  ],
  'Germany': [
    'Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hesse',
    'Lower Saxony', 'Mecklenburg-Vorpommern', 'North Rhine-Westphalia', 'Rhineland-Palatinate',
    'Saarland', 'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia'
  ],
  'India': [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat',
    'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
    'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
    'Uttarakhand', 'West Bengal', 'Delhi', 'Jammu and Kashmir', 'Ladakh'
  ],
  'Italy': [
    'Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli-Venezia Giulia',
    'Lazio', 'Liguria', 'Lombardy', 'Marche', 'Molise', 'Piedmont', 'Puglia', 'Sardinia', 'Sicily',
    'Trentino-Alto Adige', 'Tuscany', 'Umbria', 'Valle d\'Aosta', 'Veneto'
  ],
  'Japan': [
    'Hokkaido', 'Aomori', 'Iwate', 'Miyagi', 'Akita', 'Yamagata', 'Fukushima', 'Ibaraki',
    'Tochigi', 'Gunma', 'Saitama', 'Chiba', 'Tokyo', 'Kanagawa', 'Niigata', 'Toyama',
    'Ishikawa', 'Fukui', 'Yamanashi', 'Nagano', 'Gifu', 'Shizuoka', 'Aichi', 'Mie',
    'Shiga', 'Kyoto', 'Osaka', 'Hyogo', 'Nara', 'Wakayama', 'Tottori', 'Shimane',
    'Okayama', 'Hiroshima', 'Yamaguchi', 'Tokushima', 'Kagawa', 'Ehime', 'Kochi',
    'Fukuoka', 'Saga', 'Nagasaki', 'Kumamoto', 'Oita', 'Miyazaki', 'Kagoshima', 'Okinawa'
  ],
  'Malaysia': [
    'Johor', 'Kedah', 'Kelantan', 'Kuala Lumpur', 'Labuan', 'Malacca', 'Negeri Sembilan', 'Pahang',
    'Penang', 'Perak', 'Perlis', 'Putrajaya', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu'
  ],
  'Mexico': [
    'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas', 'Chihuahua',
    'Coahuila', 'Colima', 'Durango', 'Estado de México', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco',
    'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo',
    'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán',
    'Zacatecas'
  ],
  'South Africa': [
    'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga', 'Northern Cape',
    'North West', 'Western Cape'
  ],
  'United Kingdom': [
    'England', 'Scotland', 'Wales', 'Northern Ireland'
  ],
  'United States': [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware',
    'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
    'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
    'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
    'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
    'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
  ]
};
